Switch pandoc over to use YAML files for configs and metadata
Also just CI config accordingly

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -15,7 +15,7 @@ default:
             # Return all found *.pdf-files using wildcard.
             # For example, a thesis and the accompanying presentation.
             - "*.pdf"
-    # Run job 'only' if it fulfills certain criteria:
+    # Run job 'only' if it fulfills certain criteria (BETTER: use `rules`):
     # only:
         # - tags
 
@@ -23,6 +23,9 @@ default:
 stages:
     - prepare
     - build
+
+variables:
+  README_BASENAME: "README"
 
 insert_git_metadata:
     stage: prepare
@@ -43,11 +46,17 @@ insert_git_metadata:
         # Employ and use capture group \1 to replace current LaTeX command
         # (given by key in array) by corresponding value for that key.
         # Run on all class files (cls) found. Only do it once (no global option to sed),
-        # for safety: \newcommand should only occur once anyway.
+        # for safety: the relevant \newcommand should only occur once.
+        # Checking with `grep` is simpler/clearer than using sed's `q` option.
         - |
             for k in "${!GITINFO[@]}"
                 do
-                    sed -i "s~\(newcommand\*{\\\\$k}\){.*}~\1{${GITINFO[$k]}}~" *.cls
+                    grep --silent "${k}" *.cls || \
+                        { \
+                            echo "Failed to find (and therefore replace) '${k}'." && \
+                            exit 1; \
+                        };
+                    sed --in-place "s~\(newcommand\*{\\\\$k}\){.*}~\1{${GITINFO[$k]}}~" *.cls
                 done
     # Hand the processed *.cls file(s) to the next stage:
     artifacts:
@@ -57,6 +66,8 @@ insert_git_metadata:
             # default non-modified one.
             - "*.cls"
     needs: []
+    # This *shouldn't* fail, but failure is not catastrophic:
+    allow_failure: true
 
 build_latex:
     stage: build
@@ -69,24 +80,22 @@ build_latex:
         # Configure latexmk tool using '.latexmkrc' in project root.
         # After the run, display the relevant rules (for debugging).
         - latexmk --rules
-    # 'dependencies' vs 'needs' is not yet clear, it is not broadly documented currently
-    dependencies:
-        - insert_git_metadata
     needs:
-        - insert_git_metadata
+        - job: insert_git_metadata
+          # Also get that job's artifacts (like what `dependencies` used to do):
+          artifacts: true
 
 build_pandoc:
     stage: build
     script:
-        # Replace date metadata with current date.
-        # Escape because of colon in script command.
-        - 'sed -i "s~\(^date: \)\".*\"~\1\"$(date +"%B %-d, %Y")\"~" README.md'
-        # pandoc looks for template with .latex suffix in current dir
-        # Use lualatex for Unicode support
+        # Provide dynamic metadata for the date. All other settings are in the `defaults`
+        # file.
         - |
-            pandoc README.md \
-            --template eisvogel --pdf-engine=lualatex --number-sections \
-            -o README.pdf
+            pandoc \
+                --defaults=pandoc/defaults.yaml \
+                --metadata=date:$(date --iso-8601) \
+                --output=${README_BASENAME}.pdf \
+                ${README_BASENAME}.md
     # Despite being in a later stage, specifying that this particular jobs 'needs'
     # no other job allows it run immediately, leading to concurrent running of stages
     # which would otherwise run serially, speeding up the pipeline
